title: "Home"
description: ""
theme: minima
url: https://nausadmiyan.github.io
github_username: nausadmiyan

header_pages:
  - about.md
  - research.md
  - works.md
  - contact.md

minima:
  skin: auto
  social_links:
    - platform: google_scholar
      user_url: https://scholar.google.com/citations?user=orlzgpMAAAAJ&hl=en
    - platform: github
      user_url: https://github.com/nausadmiyan

plugins:
  - jekyll-feed

author: Nausad Miyan

nav:
  - title: About me
    url: /about/
  - title: Research
    url: /research/
  - title: Works
    url: /works/
    children:
      - title: Publications
        url: /works/publications/
      - title: Portfolio
        url: /works/portfolio/
      - title: Theses
        url: /works/theses/
      - title: Intellectual Properties
        url: /works/intellectual-properties/
      - title: Software
        url: /works/software/
  - title: Contact
    url: /contact/

# Footer style knobs you can edit anytime
footer:
  font_size: 14px
  line_height: 1.2
  padding: "4px 0"
  bg: "#f8f8f8"
  align: center
